//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test205sye.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        public int ID { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Sale { get; set; }
        public int Price { get; set; }
        public string Photo { get; set; }
        public int Order { get; set; }
        public int Name { get; set; }
    
        public virtual Merch Merch { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
